logging:
  level:
    jdbc:
      sqlonly: fatal
      resultsettable: info
      sqltiming: info
      audit: fatal
      resultset: fatal
      connection: fatal
    org:
      springframework:
        orm: debug

log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
  trim:
    sql:
      extrablanklines: false

spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          fetch_size: 20
          batch_versioned_data: true
#        javax.persistence.sharedCache.mode: ENABLE_SELECTIVE
        javax.cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider
          uri: classpath:ehcache.xml
        cache:
          use_second_level_cache: true
          default_cache_concurrency_strategy: read-write
          use_minimal_puts: true
          region.factory_class: jcache
          use_query_cache: true
          use_structured_entries: true

    hibernate:
      ddl-auto: create-drop